# Generated by Django 2.0.4 on 2018-04-13 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, help_text='How many animals? (eg. fish in tank)')),
                ('pyrat_id', models.CharField(max_length=200)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('pyrat_lab_id', models.CharField(max_length=200)),
                ('day_of_birth', models.DateField()),
                ('line', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], max_length=2)),
                ('location', models.CharField(max_length=200)),
                ('mutations', models.TextField(blank=True, null=True)),
                ('licence_number', models.CharField(max_length=200)),
                ('available_from', models.DateField(default=datetime.datetime(2018, 4, 13, 12, 32, 22, 42659))),
                ('available_to', models.DateField(default=datetime.datetime(2018, 4, 27, 12, 32, 22, 42740))),
                ('new_owner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('responsible_for_lab', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='animals.Lab')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='responsible_person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='animals.Person'),
        ),
    ]
