# Generated by Django 2.0.4 on 2018-04-16 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20180413_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='available_from',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='animal',
            name='available_to',
            field=models.DateField(default=datetime.datetime(2018, 4, 30, 9, 37, 43, 84183)),
        ),
    ]
