# Generated by Django 2.0.4 on 2018-04-16 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20180416_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='pyrat_id',
            new_name='external_id',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='pyrat_lab_id',
            new_name='external_lab_id',
        ),
        migrations.AlterField(
            model_name='animal',
            name='available_to',
            field=models.DateField(default=datetime.datetime(2018, 4, 30, 11, 11, 25, 896092)),
        ),
    ]
