# Generated by Django 2.0.4 on 2018-04-16 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20180416_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('mouse', 'mus musculus'), ('fish', 'fish'), ('u', 'unknown')], default='mouse', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='available_to',
            field=models.DateField(default=datetime.datetime(2018, 4, 30, 13, 29, 33, 631060)),
        ),
    ]
