# Generated by Django 2.0.4 on 2018-04-16 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20180416_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('mouse', 'mus musculus'), ('fish', 'fish'), ('u', 'unknown')], default='mouse', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='available_to',
            field=models.DateField(default=datetime.datetime(2018, 4, 30, 13, 31, 17, 561150)),
        ),
    ]
