# Generated by Django 2.0.4 on 2018-04-20 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_auto_20180416_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='amount',
            field=models.PositiveIntegerField(default=1, help_text='How many animals? (eg. fish in tank)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='available_to',
            field=models.DateField(default=datetime.datetime(2018, 5, 4, 9, 38, 54, 977358)),
        ),
        migrations.AlterField(
            model_name='animal',
            name='entry_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
