# Generated by Django 2.0.4 on 2018-05-14 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_auto_20180420_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='organ_type',
            field=models.CharField(choices=[('bladder', 'bladder'), ('brain', 'brain'), ('heart', 'heart'), ('kidney', 'kidney'), ('liver', 'liver'), ('lung', 'lung'), ('other', 'other'), ('spleen', 'spleen'), ('whole animal', 'whole animal')], default='whole animal', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('fish', 'fish'), ('fly', 'fly'), ('mouse', 'mouse'), ('unknown', 'unknown'), ('worm', 'worm')], default='mouse', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='available_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='available_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='comment',
            field=models.TextField(blank=True, help_text='Comments, such as individual organs to be offered', null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='location',
            field=models.ForeignKey(help_text='Where is the animal housed?', on_delete=django.db.models.deletion.CASCADE, to='animals.Location'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='new_owner',
            field=models.CharField(blank=True, help_text='Person claiming this animal for themselves', max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='responsible_person',
            field=models.ForeignKey(default=0, help_text='Person who is responsible in the lab for dealing with the animals', on_delete=django.db.models.deletion.CASCADE, to='animals.Person'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], help_text='Select "unknown" if multiple animals.', max_length=2),
        ),
    ]
