# Generated by Django 2.0.4 on 2018-06-01 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_auto_20180529_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='organ_type',
        ),
        migrations.AlterField(
            model_name='animal',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animal',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='external_id',
            field=models.CharField(help_text='ID of animal in eg. PYRAT', max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='external_lab_id',
            field=models.CharField(help_text='ID of lab in eg. PYRAT', max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='line',
            field=models.CharField(help_text='genetic trait of animal', max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='mutations',
            field=models.TextField(blank=True, help_text='Describe the mutations of this line in as much detail as possible', null=True),
        ),
    ]
