# Generated by Django 2.0.4 on 2018-06-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_auto_20180601_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='external_id',
            new_name='database_id',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='external_lab_id',
            new_name='lab_id',
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('fish', 'fish'), ('mouse', 'mouse')], default='mouse', max_length=100),
        ),
    ]
