# Generated by Django 2.0.4 on 2018-06-04 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0012_auto_20180604_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, help_text='How many organs?')),
                ('animal_type', models.CharField(choices=[('fish', 'fish'), ('mouse', 'mouse'), ('unknown', 'unknown')], default='mouse', max_length=100)),
                ('organ_type', models.CharField(choices=[('bladder', 'bladder'), ('bone marrow', 'bone marrow'), ('brain', 'brain'), ('genitals', 'genitals'), ('heart', 'heart'), ('intestine', 'intestine'), ('kidney', 'kidney'), ('liver', 'liver'), ('lungs', 'lungs'), ('spleen', 'spleen'), ('stomach', 'stomach'), ('other', 'other')], max_length=100)),
                ('database_id', models.CharField(help_text='ID of animal in eg. PYRAT', max_length=200)),
                ('lab_id', models.CharField(help_text='ID of lab in eg. PYRAT', max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('day_of_birth', models.DateField()),
                ('day_of_death', models.DateField()),
                ('method_of_killing', models.CharField(choices=[('CO2', 'CO2'), ('mazeration', 'mazeration'), ('other', 'other')], max_length=100)),
                ('killing_person', models.CharField(help_text='Person who is responsible for killing the animal', max_length=200)),
                ('line', models.CharField(help_text='genetic trait of animal', max_length=200)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], help_text='Select "unknown" if multiple animals.', max_length=2)),
                ('mutations', models.TextField(blank=True, help_text='Describe the mutations of this line in as much detail as possible', null=True)),
                ('licence_number', models.CharField(max_length=200)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('comment', models.TextField(blank=True, help_text='Comments, such as individual organs to be offered', null=True)),
                ('new_owner', models.CharField(blank=True, help_text='Person claiming this animal for themselves', max_length=200)),
                ('added_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Where is the animal housed?', on_delete=django.db.models.deletion.CASCADE, to='animals.Location')),
                ('responsible_person', models.ForeignKey(default=0, help_text='Person who is responsible in the lab for dealing with the animals', on_delete=django.db.models.deletion.CASCADE, to='animals.Person')),
            ],
        ),
    ]
