# Generated by Django 2.0.4 on 2018-06-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0014_auto_20180604_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='killing_person',
            field=models.EmailField(help_text='Email address of the person who is responsible for killing the animal', max_length=254),
        ),
    ]
