# Generated by Django 2.0.4 on 2018-06-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0015_auto_20180604_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organ',
            name='new_owner',
        ),
    ]
