# Generated by Django 2.0.6 on 2018-06-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0016_remove_organ_new_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='database_id',
            field=models.CharField(blank=True, help_text='ID of animal in eg. PYRAT', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organ',
            name='database_id',
            field=models.CharField(blank=True, help_text='ID of animal in eg. PYRAT', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organ',
            name='licence_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='organ',
            name='method_of_killing',
            field=models.CharField(choices=[('CO2', 'CO2'), ('cervicale dislocation', 'cervicale dislocation'), ('decapitation', 'decapitation'), ('blood withdrawl', 'blood withdrawl'), ('finale heart punction', 'finale heart punction'), ('overdose anaesthetics', 'overdose anaesthetic'), ('other', 'other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='organ',
            name='organ_type',
            field=models.CharField(choices=[('bladder', 'bladder'), ('bone marrow', 'bone marrow'), ('brain', 'brain'), ('genitals', 'genitals'), ('heart', 'heart'), ('intestine', 'intestine'), ('kidney', 'kidney'), ('liver', 'liver'), ('lungs', 'lungs'), ('spleen', 'spleen'), ('stomach', 'stomach'), ('other', 'other')], help_text='Organ type which is not available', max_length=100),
        ),
    ]
