# Generated by Django 2.0.6 on 2018-06-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0018_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='change_type',
            field=models.CharField(choices=[('new', 'new'), ('adaption', 'adaption'), ('bugfix', 'bugfix'), ('deletion', 'deletion')], default='adaption', max_length=100),
        ),
    ]
