# Generated by Django 2.0.6 on 2018-06-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0019_auto_20180625_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bladder', 'bladder'), ('bone marrow', 'bone marrow'), ('brain', 'brain'), ('genitals', 'genitals'), ('heart', 'heart'), ('intestine', 'intestine'), ('kidney', 'kidney'), ('liver', 'liver'), ('lungs', 'lungs'), ('spleen', 'spleen'), ('stomach', 'stomach'), ('other', 'other')], help_text='Organ type which is not available', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='organ',
            name='organ_type',
        ),
    ]
