# Generated by Django 2.0.6 on 2018-06-25 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0020_auto_20180625_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='organ_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='animals.Organtype'),
        ),
        migrations.AlterField(
            model_name='organtype',
            name='name',
            field=models.CharField(choices=[('bladder', 'bladder'), ('bone marrow', 'bone marrow'), ('brain', 'brain'), ('genitals', 'genitals'), ('heart', 'heart'), ('intestine', 'intestine'), ('kidney', 'kidney'), ('liver', 'liver'), ('lungs', 'lungs'), ('spleen', 'spleen'), ('stomach', 'stomach'), ('other', 'other')], default='mouse', help_text='Organ type which is not available', max_length=100),
        ),
    ]
