# Generated by Django 2.0.6 on 2018-06-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0022_auto_20180625_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organ',
            name='organ_type',
        ),
        migrations.AddField(
            model_name='organ',
            name='organ_type',
            field=models.ManyToManyField(to='animals.Organtype'),
        ),
    ]
