# Generated by Django 2.0.6 on 2018-06-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0023_auto_20180625_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organtype',
            name='name',
            field=models.CharField(choices=[('bladder', 'bladder'), ('bone marrow', 'bone marrow'), ('brain', 'brain'), ('genitals', 'genitals'), ('heart', 'heart'), ('intestine', 'intestine'), ('kidney', 'kidney'), ('liver', 'liver'), ('lungs', 'lungs'), ('spleen', 'spleen'), ('stomach', 'stomach'), ('other', 'other')], help_text='Organ type which is not available', max_length=100),
        ),
    ]
